### PR TITLE
consider my repo

### PR DESCRIPTION
**Pull request by Dhiraj23082000**
updated namecard
first i forked repo and then cloned it to my windows.then made changes in it and finally push it to origin.
Merge my pull request to your repo.

### CODE REVIEW

**Comment by jmig5776** [comment]
Your changes are not as per guidelines. You are required only to add a single namecard and not change the entire file.

**Comment by Dhiraj23082000** [comment]
now i made changes according to the assignment,is it correct?

**Comment by jmig5776** [comment]
Sorry your index.html is older version, please pull the latest master i.e rebase to upstream to get latest version of index.html. Your file only includes 3 cards except you while you can checkout the latest `index.html` in our repository

**Comment by jmig5776** [comment]
I had edited your changes. But in future always make sure you are at the latest master to create pull request to avoid conflicts to occur.

**Comment by jmig5776** [comment]
Congrats!! Its merged now. You can look your namecard on the site now.

**Pull request merged**
