### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by shalini-18**
Added namecard and required image as per the guidelines of the challenge.

### CODE REVIEW

**Comment by jmig5776** [comment]
@shalini-18 You have done nice work. But in the PR you are also adding [this image](https://github.com/COPS-IITBHU/cops_namecards/pull/16/files?short_path=c97d30c#diff-c97d30c8b993b802f6c3e78cde4121b3) outside of images directory, please delete that from the PR. If you find any difficulties then let me know. Moreover I had edited your description. Let me know after you delete it.

**Comment by shalini-18** [comment]
I am not able to delete the image from PR!

**Comment by shalini-18** [comment]
Can I send a new PR without the image? Because I am not able to delete the image.

**Comment by jmig5776** [comment]
Okay No problem!!. Let me know if you got any problem.

**Comment by jmig5776** [comment]
Its merged.
Cheers!!

**Pull request merged**
